### ISSUE TITLE
Todo for the game

### ISSUE THREAD

**Issue by shinspiegel** [shinspiegel/godot_playground#1]
What do I need to do?

- [x] Player
    - [x] Basic logic for a platformer
    - [x] States
        - [x] Move
        - [x] Jump
        - [x] Attack
        - [x] Hit
        - [x] Death
        - [ ] ~~Push Forward~~
        - [x] Dash Forward
    - [x] Power ups
        - [x] Dash forward (consume mana)
        - [x] Double Jump (consume mana)
    - [x] Keep record of coins and mana throught the stages 
- [ ] Make Levels
    - [ ] Entry screen 
    - [x] Level 0 (Tutorial)
    - [ ] Level 1
    - [ ] Level 2 (+ Boss battle)
    - [ ] Ending 
- [x] UI
    - [x] Show life
    - [x] Show mana
    - [x] Show coin
- [x] Boxes
    - [x] Hitbox 
    - [x] Hurtbox
        - [x] Invencibility time 
- [x] Pickables
    - [x] Potion
    - [x] Mana
    - [x] Coin
- [x] Environment
    - [x] Skipes
    - [x] Vase
    - [x] Backgroud
    - [x] Ceiling trap
    - [x] Door Open/Close
    - [ ] ~~Box pushable~~
- [ ] Enemies
    - [x] Worm 
    - [x] Slime
    - [ ] Mushroom
    - [x] Goblin
    - [ ] Fly
    - [x] Bomber Goblin
